07/02/2021
krzema12/kotlin-python pull request #5
Opened 2021-07-02 17:31 UTC by SerVB

2021-07-06 19:58 UTC, krzema12 requested changes
Could you also update this file https://github.com/krzema12/kotlin-1/blob/python-backend/python/experiments/failed-tests.txt? It simply contains lines from the output of box tests which contain "FAILED", somewhere in README it's written how to generate it. The goal is to not only see the increase of tests, but also see which tests now pass after a given change. This in turn can suggest other low-hanging fruits which may lead to more tests passing :)

2021-07-06 20:01 UTC, SerVB commented
Oh, thanks, I've totally forgotten about that file. Sure, I'll add a commit in this PR.

It's a good idea with the CI checking the file, I guess I will manage to add it too.

2021-07-17 17:19 UTC, SerVB commented
CI is done in #8

2021-07-17 18:01 UTC, krzema12 approved these changes

2021-07-17 18:08 UTC, merged